### ISSUE TITLE
The function of held-out prompts

### ISSUE THREAD

**Issue by Lancelot1998** [holarissun/Prompt-OIRL#2]
Hi Hao, thank you so much for your wonderful work!

I have a question about the function of held-out prompts. They are mainly used for evaluating the generalization ability of the trained reward function, right? I mean, with the trained reward function, we can feed any of the x and prompted x and get the predicted reward. I am not sure whether my understanding is correct.

Hope to hear from you. Thank you so much ^_^

**Comment by holarissun** [comment]
Thank you for your interest in our work!

Yes, the held-out prompts are used for evaluation only --- so we need to have a fixed set and corresponding golden answers to calculate the accuracies/precisions, etc.

In practice, the test prompting strategies can be any prompts.

Hope this helps :) 

Best,
Hao

**Comment by Lancelot1998** [comment]
Yes, thank you so much for the answer! It helps me a lot.
