### ISSUE TITLE
dataset_gsm8k

### ISSUE THREAD

**Issue by HxDi520** [holarissun/Prompt-OIRL#3]
File "llama_exps/llama_step1_gen_offline.py", line 9, in <module>
    from dataset_gsm8k import get_examples_gsm8k
ModuleNotFoundError: No module named 'dataset_gsm8k'
I could not find the module needed and the huggingface provide the code 

from datasets import load_dataset
dataset = load_dataset("gsm8k")

**Comment by holarissun** [comment]
Thanks for your interest in our work and for your comment!

Sorry for missing a functional .py file in the previous version, I've uploaded the file needed

you probably need to replace the path from the current "../PromptingRLHF/data/" to the folder on your side.

the files in the data folder are
 - train.jsonl
 - test.jsonl
 - train_socratic.jsonl
 - test_socratic.jsonl
 - example_model_solutions

```

import json
import os
import re
import torch


def read_jsonl(path: str):
    with open(path) as fh:
        return [json.loads(line) for line in fh.readlines() if line]


def get_examples_gsm8k(split):
    path = os.path.join("../PromptingRLHF/data/", f"{split}.jsonl")
    examples = read_jsonl(path)

    for ex in examples:
        ex.update(question=ex["question"] + "\n")
        ex.update(answer=ex["answer"] + "<|endoftext|>")

    print(f"{len(examples)} {split} examples")
    return examples


ANS_RE = re.compile(r"#### (\-?[0-9\.\,]+)")
INVALID_ANS = "[invalid]"


def extract_answer(completion):
    match = ANS_RE.search(completion)
    if match:
        match_str = match.group(1).strip()
        match_str = match_str.replace(",", "")
        return match_str
    else:
        return INVALID_ANS


def is_correct(model_completion, gt_example):
    gt_answer = extract_answer(gt_example["answer"])
    assert gt_answer != INVALID_ANS
    return extract_answer(model_completion) == gt_answer


class GSMDataset(torch.utils.data.Dataset):
    def __init__(self, tokenizer, examples, loss_on_prefix=True):
        self.examples = examples
        self.qns = [ex["question"] for ex in self.examples]
        self.ans = [ex["answer"] for ex in self.examples]
        self.qns = tokenizer(self.qns, padding=False)
        self.ans = tokenizer(self.ans, padding=False)
        self.loss_on_prefix = loss_on_prefix
        self.max_len = max(
            [
                len(self.qns["input_ids"][i]) + len(self.ans["input_ids"][i])
                for i in range(len(self.examples))
            ]
        )
        print(f"Max tokens: {self.max_len}")

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        qn_tokens = self.qns["input_ids"][idx]
        ans_tokens = self.ans["input_ids"][idx]
        pad_tokens = [0] * (self.max_len - len(qn_tokens) - len(ans_tokens))
        tokens = qn_tokens + ans_tokens + pad_tokens
        mask = (
            ([int(self.loss_on_prefix)] * len(qn_tokens))
            + ([1] * len(ans_tokens))
            + ([0] * len(pad_tokens))
        )
        tokens = torch.tensor(tokens)
        mask = torch.tensor(mask)
        return dict(input_ids=tokens, attention_mask=mask)

```



Hope this helps! 

Best,
Hao

**Comment by HxDi520** [comment]
Thanks  for your reply.lol
But I found another problem with
ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu11==11.10.3.66 (from versions: 0.0.1.dev5, 0.0.1)
ERROR: No matching distribution found for nvidia-cublas-cu11==11.10.3.66
maybe it just could not be installed through pip just a fews days before.
then I tried this command
conda install cuda -c nvidia
UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/osx-64::__osx==10.16=0
  - feature:|@/osx-64::__osx==10.16=0
  - cuda -> __linux
  - python==3.10 -> ncurses[version='>=6.2,<7.0.0a0'] -> __osx[version='>=10.9']

Your installed version is: 10.16
it does not work for macos./cry
I am tring other ways to fix it.

**Comment by holarissun** [comment]
Hey,

It seems like this error is raised due to the cuda that is not a core component in this specific project. For easier reproduction, I've added a ```requirement.txt``` file in the recent push.

Hope it helps :) 

Best,
Hao

**Comment by HxDi520** [comment]
[Grin]  waiting for your update～

**Comment by holarissun** [comment]
please find the ```requirement.txt``` file at [this link](https://github.com/holarissun/Prompt-OIRL/blob/main/requirements.txt)

**Comment by HxDi520** [comment]
I deleted the code corresponding to nvidia and reinstall the virtual env.
then it came with 
Traceback (most recent call last):
  File "/Users/zhaihaixu/projects/Prompt-OIRL-main/llama_exps/llama_step1_gen_offline.py", line 24, in <module>
    from llama import Llama
ModuleNotFoundError: No module named 'llama'
I don't not how to config the model and the dateset to your project.~[grin]

**Comment by holarissun** [comment]
Please check the step 1 in the current readme.md file.

If you would like to reproduce the offline dataset, for example, with the llama2 model, you need to work under the dir of

``` git@github.com:facebookresearch/llama.git```

(this means you need to follow the installation instructions of the official llama --- such that you can run llama on your machine locally)

Then, move both ```Prompt-OIRL/llama_exps/dataset_gsm8k.py``` and ```Prompt-OIRL/llama_exps/llama_step1_gen_offline.py``` to the llama folder


and finally, run 
```
torchrun --nproc_per_node 1 llama_step1_gen_offline.py \
   --ckpt_dir llama-2-7b-chat/ \
   --tokenizer_path tokenizer.model \
   --max_seq_len 512 --max_batch_size 8 --prompt_idx 0 --dataset_eval gsm8k
```
